[[language]]
name = "latex"
file-types = [ "tex" ]
injection-regex = "tex"
language-server = { command = "texlab" }

[language.config.texlab]
auxDirectory = "build"

[language.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language.config.texlab.build]
forwardSearchAfter = true
onSave = true
executable = "tectonic"
args = [ "%f", "--outdir=build" ]
