#!/bin/sh



# {{ BINDINGS }}
pgrep -x sxhkd > /dev/null || sxhkd &
# {{ BINDINGS }}



# {{ WORKSPACES }}
bspc monitor -d 1 2 3 4 5 6 7 8
# {{ WORKSPACES }}



# {{ DECORATIONS }}
bspc config border_width 3
bspc config window_gap 15
bspc config normal_border_color "#F07342"
bspc config focused_border_color "#CF2241"
# {{ DECORATIONS }}



# {{ TILING }}
bspc config split_ratio 0.57
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle true
# {{ TILING }}



# {{ FOCUS }}
bspc config focus_follows_pointer true
# {{ FOCUS }}



# {{ RULES }}
bspc rule -a Zathura state=tiled
# {{ RULES }}
